apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure-express-app
  template:
    metadata:
      labels:
        app: insecure-express-app
    spec:
      imagePullSecrets:
        - name: docker-registry-secret1
      containers:
        - name: insecure-express-app
          image: {{ .Values.image }}
          ports:
            - containerPort: 3000