apiVersion: v1
kind: Service
metadata:
  name: insecure-express-app
spec:
  selector:
    app: insecure-express-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP